name: Release Compiled PDF
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.otf
            ./fonts/*.ttf

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "resume pdf"
          files: |
            resume.pdf
